### ISSUE TITLE
執行至docker-compose up時出錯

### ISSUE THREAD

**Issue by cgl0408** [twtrubiks/docker-tutorial#11]
錯誤訊息:web_1  | python: can't open file 'manage.py': [Errno 2] No such file or directory
檔案配置:
![image](https://user-images.githubusercontent.com/41777892/128592643-13de81bd-a941-403c-b944-3e12cceb13ae.png)
請問這是什麼地方出錯呢

**Comment by twtrubiks** [comment]
你的資料夾位置似乎和我的 repo 不太一樣, 你重新 clone 一次, 依照我的步驟再操作一次.

**Comment by cgl0408** [comment]
您好，感謝你的回覆
我發現您的教學影片與github的教學題材內容有些出入
像是Dockerfile
![image](https://user-images.githubusercontent.com/41777892/128693707-946990e8-8233-4521-becf-11f684523d6e.png)
該紅框在影片中是api而非docker_api
以及docker-compose.yml也有類似的出入
另外影片中只有1:46可以看見您檔案位置子資料夾"api"的結構
所以我只模仿了api資料夾

我也嘗試過將"docker-compose.yml"的command改成絕對路徑執行如下
`command: python D:\\PythonEnvs\\django-rest-framework-tutorial-master\\api\\manage.py runserver 0.0.0.0:8000`
其最後結果都與原本的錯誤一樣，不過依照您的提示 有新增了一個新的錯誤訊息
` File "docker\api\client.py", line 268, in _raise_for_status
  File "requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: 
http+docker://localnpipe/v1.41/containers/c173780434e11c3131997bd09fa1d0fe878dd38391749980428cf372b1516de5/attach?logs=0&stdout=1&stderr=1&stream=1`

以下是我的資料夾結構
![image](https://user-images.githubusercontent.com/41777892/128694432-ebd1f8c6-5ae8-4dc2-bd41-9cff399bd2f3.png)
![image](https://user-images.githubusercontent.com/41777892/128694449-bc200fd5-2510-460d-83d9-b6d6e331e331.png)
![image](https://user-images.githubusercontent.com/41777892/128694504-28e205bf-220b-4425-812b-1bd5c3f676c9.png)
![image](https://user-images.githubusercontent.com/41777892/128694535-a6af5ec8-f309-4932-8b87-a2c36b66d773.png)
若能指點一二將感激不盡
