### ISSUE TITLE
您好，關於 Readme 中 port 的部分

### ISSUE THREAD

**Issue by William-Mou** [twtrubiks/docker-tutorial#5]
## 中間這部分是不是應該改成將 local 80 port 導向 dcoker container 80 port？

![](https://i.imgur.com/Ljh4sm4.png)

(抱歉不小心按到發布，造成標題不清晰0.0)

**Comment by twtrubiks** [comment]
Hi  @William-Mou 的確是我筆誤了，我會再將它修正，謝謝提醒。
的確是 80 port 才對，感謝校正。
